name: Production Build Verification

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install root dependencies
        run: npm ci
        
      - name: Build frontend
        working-directory: ./client
        run: npm ci && npm run build
        env:
          NODE_ENV: production
          PUBLIC_API_URL: ${{ vars.API_URL || 'http://localhost:3000/api' }}

      - name: Build backend
        working-directory: ./server
        run: npm ci && npm run build
        env:
          NODE_ENV: production
          SUPABASE_URL: ${{ vars.SUPABASE_URL || 'https://example.supabase.co' }}
          SUPABASE_KEY: ${{ vars.SUPABASE_KEY || 'placeholder-key-for-build' }}
          OPENROUTER_API_KEY: ${{ vars.OPENROUTER_API_KEY || 'placeholder-key-for-build' }}
          
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            client/dist
            server/dist
