name: Pull Request Workflow

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      
      - name: Install client dependencies
        run: npm run install:client
      
      - name: Install server dependencies
        run: npm run install:server

      - name: Lint client
        run: cd client && npm run lint
        
      - name: Lint server
        run: cd server && npm run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        
      - name: Install client dependencies
        run: npm run install:client
      
      - name: Install server dependencies
        run: npm run install:server

      - name: Build client
        run: npm run build:client
        
      - name: Build server
        run: npm run build:server

  status-comment:
    name: Status Comment
    runs-on: ubuntu-latest
    needs: [lint, build]
    if: ${{ success() }}
    steps:
      - name: Create status comment
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ All checks have passed! The PR is ready for review.'
            })
